import Head from "next/head";
import Hero from "@components/Hero";
import Main from "@components/Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Captain Run</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <Hero/>
      <Main/>
    </div>

  );
}
